# .github/repository_config.yml - Core Protection Configuration
repository_protection:
  visibility: public  # Options: public, private, internal
  fork_restrictions: enabled
  automated_security_features:
    dependency_scanning: enabled
    secret_scanning: enabled
    code_scanning: enabled
  branch_protection:
    require_signed_commits: true
    require_linear_history: true
    allow_force_pushes: false
    deletion_restriction: true
